#!/usr/bin/env python3
"""
ProKerala API Credentials Setup Script
=====================================

This script helps you set up your ProKerala API credentials for the birth chart system.
"""

import os
import sys
from pathlib import Path

def main():
    print("🕉️  JyotiFlow ProKerala API Setup")
    print("=" * 50)
    print()
    
    # Get credentials from user
    print("Please enter your ProKerala API credentials:")
    print("(You can get these from https://api.prokerala.com/)")
    print()
    
    client_id = input("ProKerala Client ID: ").strip()
    client_secret = input("ProKerala Client Secret: ").strip()
    
    if not client_id or not client_secret:
        print("❌ Error: Both Client ID and Client Secret are required!")
        sys.exit(1)
    
    # Create .env file
    backend_dir = Path(__file__).parent
    env_file = backend_dir / ".env"
    
    # Read existing .env file if it exists
    existing_env = {}
    if env_file.exists():
        with open(env_file, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    existing_env[key] = value
    
    # Update with ProKerala credentials
    existing_env['PROKERALA_CLIENT_ID'] = client_id
    existing_env['PROKERALA_CLIENT_SECRET'] = client_secret
    
    # Write updated .env file
    with open(env_file, 'w') as f:
        f.write("# JyotiFlow Environment Variables\n")
        f.write("# Generated by setup_prokerala_credentials.py\n\n")
        
        # Write ProKerala credentials first
        f.write("# ProKerala API Configuration\n")
        f.write(f"PROKERALA_CLIENT_ID={client_id}\n")
        f.write(f"PROKERALA_CLIENT_SECRET={client_secret}\n\n")
        
        # Write other environment variables
        for key, value in existing_env.items():
            if key not in ['PROKERALA_CLIENT_ID', 'PROKERALA_CLIENT_SECRET']:
                f.write(f"{key}={value}\n")
    
    print()
    print("✅ ProKerala credentials saved to .env file!")
    print(f"📁 Location: {env_file}")
    print()
    print("🎯 Next steps:")
    print("1. Make sure your DATABASE_URL is set in production environment")
    print("2. Deploy your backend with the new credentials")
    print("3. Test the birth chart generation!")
    print()
    print("🔗 Test your setup:")
    print("   Visit: https://your-domain.com/birth-chart")
    print("   Or use curl:")
    print('   curl -X POST "https://your-domain.com/api/spiritual/birth-chart" \\')
    print('     -H "Content-Type: application/json" \\')
    print('     -d \'{"birth_details": {"date": "1983-09-07", "time": "10:10", "location": "Jaffna, Sri Lanka"}}\'')
    print()

if __name__ == "__main__":
    main()