-- Fix user_id type mismatches across all tables
-- This migration consolidates all user_id columns to INTEGER
-- Auto-generated by Database Self-Healing System

BEGIN;

-- 1. Fix sessions table
ALTER TABLE sessions 
ALTER COLUMN user_id TYPE INTEGER 
USING user_id::INTEGER;

-- 2. Fix credit_transactions table
ALTER TABLE credit_transactions 
ALTER COLUMN user_id TYPE INTEGER 
USING user_id::INTEGER;

-- 3. Fix user_purchases table
ALTER TABLE user_purchases 
ALTER COLUMN user_id TYPE INTEGER 
USING user_id::INTEGER;

-- 4. Fix avatar_sessions table
ALTER TABLE avatar_sessions 
ALTER COLUMN user_id TYPE INTEGER 
USING user_id::INTEGER;

-- 5. Fix live_chat_sessions table
ALTER TABLE live_chat_sessions 
ALTER COLUMN user_id TYPE INTEGER 
USING user_id::INTEGER;

-- 6. Add missing foreign key constraints
ALTER TABLE sessions 
ADD CONSTRAINT fk_sessions_user_id 
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE credit_transactions 
ADD CONSTRAINT fk_credit_transactions_user_id 
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE user_purchases 
ADD CONSTRAINT fk_user_purchases_user_id 
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

-- 7. Create indexes on foreign keys
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_credit_transactions_user_id ON credit_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_purchases_user_id ON user_purchases(user_id);

COMMIT;