-- Populate RAG knowledge base with comprehensive spiritual wisdom
-- This provides the foundation for dynamic content generation

-- Clear any existing migration seeded data (preserve production data)
DELETE FROM rag_knowledge_base 
WHERE metadata->>'created_for' = 'spiritual_calendar_service' 
OR source_reference LIKE 'https://jyotiflow.com/%'
OR title IN ('The Path to Inner Peace', 'Meditation for Daily Life', 'Walking Meditation Wisdom');

-- Insert comprehensive spiritual wisdom content
INSERT INTO rag_knowledge_base (title, content, category, tags, source_reference, metadata) VALUES

-- Inner Peace & Meditation
('The Path to Inner Peace', 'True inner peace is not the absence of conflict, but the presence of tranquility amidst life''s storms. When we cultivate stillness within, we become unshakeable by external circumstances. Practice daily meditation, even for just 10 minutes, and watch as your inner landscape transforms. Peace is your natural state - everything else is temporary noise.', 'meditation', ARRAY['inner_peace', 'meditation', 'tranquility', 'mindfulness'], 'https://jyotiflow.com/inner-peace', '{"difficulty": "beginner", "duration": "daily", "practice_type": "meditation", "created_for": "spiritual_calendar_service"}'),

('Meditation for Daily Life', 'Meditation is not escape from reality but preparation for it. Start each morning with 5 minutes of breath awareness. Sit comfortably, close your eyes, and simply observe your breathing. When thoughts arise, gently return to the breath. This simple practice builds the foundation for mindful living throughout your day.', 'meditation', ARRAY['daily_practice', 'breathing', 'mindfulness', 'morning_routine'], 'https://jyotiflow.com/daily-meditation', '{"difficulty": "beginner", "time_needed": "5-10 minutes", "benefits": ["stress_reduction", "clarity", "peace"], "created_for": "spiritual_calendar_service"}'),

('Walking Meditation Wisdom', 'Every step can be a prayer, every breath a blessing. Walking meditation transforms ordinary movement into spiritual practice. Walk slowly, feeling each footfall, synchronized with your breathing. Let nature be your temple and movement be your prayer. This practice brings mindfulness into action and action into mindfulness.', 'meditation', ARRAY['walking_meditation', 'nature', 'movement', 'active_practice'], 'https://jyotiflow.com/walking-meditation', '{"location": "outdoors", "duration": "15-30 minutes", "difficulty": "beginner", "created_for": "spiritual_calendar_service"}'),

-- Spiritual Guidance & Wisdom
('Understanding Your Life Purpose', 'Your life purpose is not something you find externally - it emerges from within when you align with your authentic self. Pay attention to what brings you joy, what challenges ignite your passion, and what service calls to your heart. Your dharma lies at the intersection of your gifts, the world''s needs, and your deepest joy.', 'guidance', ARRAY['life_purpose', 'dharma', 'authenticity', 'service'], 'https://jyotiflow.com/life-purpose', '{"theme": "self_discovery", "approach": "reflective", "depth": "deep", "created_for": "spiritual_calendar_service"}'),

('Overcoming Life Challenges', 'Every obstacle is a teacher in disguise. When faced with difficulties, ask not "Why me?" but "What is this teaching me?" Challenges are not punishments but invitations to grow. Embrace them with curiosity rather than resistance. The very quality you need to develop is often hidden within the challenge you''re avoiding.', 'guidance', ARRAY['challenges', 'growth', 'resilience', 'learning'], 'https://jyotiflow.com/overcoming-challenges', '{"mindset": "growth", "perspective": "transformational", "application": "practical", "created_for": "spiritual_calendar_service"}'),

('The Wisdom of Patience', 'Patience is not passive waiting but active trust in divine timing. Everything unfolds according to a cosmic rhythm beyond our understanding. When you feel rushed or anxious, remember that roses don''t hurry to bloom, rivers don''t rush to the sea. Trust the process, embrace the journey, and know that your time will come.', 'guidance', ARRAY['patience', 'divine_timing', 'trust', 'surrender'], 'https://jyotiflow.com/patience-wisdom', '{"virtue": "patience", "philosophy": "surrender", "practical_tip": "trust_timing", "created_for": "spiritual_calendar_service"}'),

-- Daily Spiritual Practices
('Morning Spiritual Routine', 'How you begin your day sets the tone for everything that follows. Create a sacred morning routine: wake with gratitude, meditate for clarity, set intentions for service. Drink water mindfully, stretch your body lovingly, and step into your day as a conscious being ready to spread light wherever you go.', 'daily_practice', ARRAY['morning_routine', 'gratitude', 'intentions', 'mindful_living'], 'https://jyotiflow.com/morning-routine', '{"time": "morning", "duration": "20-30 minutes", "elements": ["gratitude", "meditation", "intention_setting"], "created_for": "spiritual_calendar_service"}'),

('Evening Reflection Practice', 'End each day with conscious reflection. What did I learn today? How did I serve? What am I grateful for? What could I improve? This evening practice transforms ordinary days into lessons and experiences into wisdom. Let each sunset be a bookmark in the story of your spiritual evolution.', 'daily_practice', ARRAY['evening_practice', 'reflection', 'gratitude', 'self_improvement'], 'https://jyotiflow.com/evening-reflection', '{"time": "evening", "practice": "journaling", "focus": "growth", "created_for": "spiritual_calendar_service"}'),

('The Power of Gratitude', 'Gratitude is the fastest way to transform your reality. What you appreciate, appreciates. Start and end each day by listing three things you''re grateful for. Include challenges - they''re gifts in disguise. Gratitude shifts your focus from what''s missing to what''s present, from scarcity to abundance.', 'daily_practice', ARRAY['gratitude', 'abundance', 'appreciation', 'transformation'], 'https://jyotiflow.com/gratitude-practice', '{"frequency": "daily", "method": "listing", "impact": "transformational", "created_for": "spiritual_calendar_service"}'),

-- Relationships & Compassion
('Cultivating Compassion', 'Compassion begins with yourself and extends to all beings. When you make mistakes, treat yourself with the same kindness you''d show a good friend. When others hurt you, remember they''re acting from their own pain. Compassion doesn''t mean accepting harmful behavior - it means responding with wisdom rather than reaction.', 'relationships', ARRAY['compassion', 'self_love', 'forgiveness', 'understanding'], 'https://jyotiflow.com/compassion', '{"focus": "universal_love", "practice": "loving_kindness", "application": "daily_life", "created_for": "spiritual_calendar_service"}'),

('Forgiveness as Freedom', 'Forgiveness is not about forgetting or condoning - it''s about freeing yourself from the prison of resentment. When you hold anger, you''re drinking poison hoping the other person will suffer. Forgiveness is the key that unlocks your own cell. Forgive not for them, but for your own peace and freedom.', 'relationships', ARRAY['forgiveness', 'freedom', 'healing', 'release'], 'https://jyotiflow.com/forgiveness', '{"purpose": "self_liberation", "method": "release", "benefit": "inner_peace", "created_for": "spiritual_calendar_service"}'),

('Sacred Relationships', 'Every relationship is a mirror reflecting your own consciousness. Difficult people show you where you need to grow. Loving people show you what''s possible. Treat every encounter as sacred - an opportunity to practice patience, compassion, or courage. Your relationships are your greatest spiritual teachers.', 'relationships', ARRAY['sacred_relationships', 'mirrors', 'growth', 'teachers'], 'https://jyotiflow.com/sacred-relationships', '{"perspective": "spiritual", "learning": "continuous", "approach": "conscious", "created_for": "spiritual_calendar_service"}'),

-- Mindfulness & Present Moment
('The Gift of Presence', 'The present moment is the only reality you truly have. The past is memory, the future is imagination - but life happens now. Practice bringing your full attention to whatever you''re doing. When eating, eat. When listening, listen. When loving, love completely. Presence is the greatest gift you can give yourself and others.', 'mindfulness', ARRAY['presence', 'present_moment', 'awareness', 'attention'], 'https://jyotiflow.com/presence', '{"focus": "now", "practice": "attention", "quality": "full_engagement", "created_for": "spiritual_calendar_service"}'),

('Mindful Breathing', 'Your breath is your most faithful companion, accompanying you from first cry to last whisper. Each inhale is a gift of life, each exhale a release of what no longer serves. When overwhelmed, return to your breath. Four counts in, hold for four, out for four. This simple practice anchors you in the present and calms the storm within.', 'mindfulness', ARRAY['breathing', 'anchor', 'calm', 'centering'], 'https://jyotiflow.com/mindful-breathing', '{"technique": "4-4-4 breathing", "effect": "calming", "accessibility": "anywhere", "created_for": "spiritual_calendar_service"}'),

('Mindful Eating Practice', 'Transform every meal into a meditation. Before eating, pause and appreciate the journey of your food from earth to plate. Chew slowly, taste fully, eat gratefully. This practice nourishes not just your body but your soul. When you eat mindfully, you honor the interconnectedness of all life.', 'mindfulness', ARRAY['mindful_eating', 'gratitude', 'connection', 'nourishment'], 'https://jyotiflow.com/mindful-eating', '{"practice": "slow_eating", "focus": "appreciation", "connection": "nature", "created_for": "spiritual_calendar_service"}'),

-- Spiritual Growth & Transformation
('Embracing Change', 'Change is the only constant in life, yet we resist it like fighting the current of a river. What if, instead, you learned to dance with change? Every ending is a beginning, every loss creates space for gain. Embrace change as life''s way of updating your soul''s software. Growth requires letting go of who you were to become who you''re meant to be.', 'growth', ARRAY['change', 'transformation', 'letting_go', 'evolution'], 'https://jyotiflow.com/embracing-change', '{"attitude": "acceptance", "metaphor": "river", "process": "continuous", "created_for": "spiritual_calendar_service"}'),

('The Journey Within', 'The longest journey you''ll ever take is the 18 inches from your head to your heart. This inner journey is more important than any external achievement. Spend time in silence, question your beliefs, explore your fears, embrace your shadows. Self-knowledge is the beginning of all wisdom and the foundation of authentic living.', 'growth', ARRAY['self_knowledge', 'inner_journey', 'authenticity', 'wisdom'], 'https://jyotiflow.com/inner-journey', '{"direction": "inward", "goal": "self_knowledge", "method": "reflection", "created_for": "spiritual_calendar_service"}'),

('Overcoming Fear', 'Fear is not your enemy - it''s a compass pointing toward your growth. What you fear most often holds the key to what you need most. Feel the fear and move forward anyway. Courage is not the absence of fear but action in spite of it. Every time you face your fears, you reclaim a piece of your power and expand your possibilities.', 'growth', ARRAY['fear', 'courage', 'growth', 'expansion'], 'https://jyotiflow.com/overcoming-fear', '{"strategy": "face_fears", "outcome": "empowerment", "mindset": "courageous", "created_for": "spiritual_calendar_service"}'),

-- Spiritual Wisdom & Philosophy
('The Illusion of Separation', 'The greatest illusion is that we are separate from each other and from the divine. In truth, we are waves in the same ocean, leaves on the same tree, stars in the same sky. When you truly understand this oneness, compassion becomes natural, service becomes joy, and love becomes your default response to life.', 'philosophy', ARRAY['oneness', 'unity', 'illusion', 'divine_connection'], 'https://jyotiflow.com/oneness', '{"concept": "non_dualism", "realization": "unity", "impact": "universal_love", "created_for": "spiritual_calendar_service"}'),

('The Art of Surrender', 'Surrender is not giving up - it''s giving in to a wisdom greater than your own. When you''ve done all you can, when you''ve planned and prepared and acted, sometimes the next step is to let go and trust. Surrender is the courage to trust life''s intelligence, to allow rather than force, to receive rather than just achieve.', 'philosophy', ARRAY['surrender', 'trust', 'letting_go', 'divine_will'], 'https://jyotiflow.com/surrender', '{"practice": "letting_go", "quality": "trust", "wisdom": "divine_timing", "created_for": "spiritual_calendar_service"}'),

('Living with Purpose', 'Purpose is not something you find in a job title or achievement - it''s how you show up in the world. Your purpose is to be the fullest expression of who you are, to serve with your unique gifts, to love without condition. When you align with this deeper purpose, every action becomes meaningful, every day becomes sacred.', 'philosophy', ARRAY['purpose', 'service', 'authenticity', 'meaning'], 'https://jyotiflow.com/purpose', '{"definition": "authentic_expression", "method": "service", "result": "fulfillment", "created_for": "spiritual_calendar_service"}'),

-- Seasonal & Cyclical Wisdom
('Spring Awakening Wisdom', 'Like nature, you too have seasons of growth and rest. Spring energy invites new beginnings, fresh starts, and planted seeds of intention. What wants to bloom in your life? What old patterns are you ready to leave behind? Embrace spring''s energy of renewal and rebirth. Your spiritual garden awaits your attention.', 'seasonal', ARRAY['spring', 'renewal', 'new_beginnings', 'growth'], 'https://jyotiflow.com/spring-wisdom', '{"season": "spring", "energy": "renewal", "focus": "new_beginnings", "created_for": "spiritual_calendar_service"}'),

('Summer Radiance Practice', 'Summer teaches us about abundance, vitality, and shining our light brightly. This is the season to express your gifts fully, to be generous with your love, to celebrate life''s abundance. Like the sun, shine without asking who you''re illuminating. Your radiance is needed in this world - don''t dim it for anyone.', 'seasonal', ARRAY['summer', 'abundance', 'radiance', 'generosity'], 'https://jyotiflow.com/summer-wisdom', '{"season": "summer", "quality": "radiance", "practice": "generous_expression", "created_for": "spiritual_calendar_service"}'),

('Autumn Wisdom of Release', 'Autumn teaches the beauty of letting go. Trees don''t cling to their leaves - they release them with grace, making way for new growth. What are you ready to release? What habits, beliefs, or relationships no longer serve your highest good? Let go with gratitude, making space for what''s meant to come.', 'seasonal', ARRAY['autumn', 'letting_go', 'release', 'gratitude'], 'https://jyotiflow.com/autumn-wisdom', '{"season": "autumn", "lesson": "release", "attitude": "graceful_letting_go", "created_for": "spiritual_calendar_service"}'),

('Winter Inner Reflection', 'Winter is nature''s invitation to go within. Like seeds resting in dark soil, this is your time for inner reflection, deep rest, and spiritual preparation. Don''t fight the quiet energy - embrace it. Use this time to journal, meditate, dream, and connect with your deepest truths. Spring will come, but first, honor the wisdom of winter.', 'seasonal', ARRAY['winter', 'reflection', 'rest', 'inner_work'], 'https://jyotiflow.com/winter-wisdom', '{"season": "winter", "energy": "introspective", "practice": "inner_reflection", "created_for": "spiritual_calendar_service"}');
